version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
      - image: "circleci/python:3.7.10"
    steps:
      - checkout
      - run:
          name: Install dependencies364
          command : sudo pip3 install -r requirements.txt && python3 main-test.py
          docker:
            - image: circleci/python:3.6.4
      - run:
          name: Install dependencies3710
          command : sudo pip3 install -r requirements.txt && python3 main-test.py
          docker:
            - image: "circleci/python:3.7.10"

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: sudo pip3 install -r requirements.txt
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
